# Add a "/" after baseurl so the css and js folders work corectly
baseurl = "https://surajmandalcell.github.io/blog"
pygmentsuseclasses = true
languageCode = "en-us"
publishDir = "public"
Title = "[ Suraj Mandal ]"
relativeURLs = true
theme = "potato-dark"
copyright = "&copy; Copyright Suraj Mandal 2018"

[params]
  paginate = 10
  twitter = "Cruelplatypus67"
  facebook = "surajmandalcell"
  github = "surajmandalcell"
  gitlab = "surajmandalcell"
  # npm = "Your npm username"
  codepen = "cruelplatypus67"
  tumblr = "cruelplatypus67"
  linkedin = "surajmandalcell"
  disqus = "Cruelplatypus67"
  # ga_api_key = "Your Google Analytics tracking id"
  subtitle = "Programmer by profession designer by passion"
  # Logo image. This is displayed ogp image.
  # logo = "/path/to/logo"
  # favicon = "/path/to/favicon"

[[menu.main]]
    name = "Blog"
    url = "https://surajmandalcell.github.io/blog"
    weight = 1

[[menu.main]]
    identifier = "theme"
    name = "Theme"
    url = "https://surajmandalcell.github.io/blog"
    weight = 2

[[menu.main]]
    name = "About"
    url = "https://surajmandalcell.github.io"
    weight = 3

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
